# Generated by Django 4.0.10 on 2023-08-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('title', models.CharField(max_length=200, null=True)),
                ('news', models.TextField(max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='list_images')),
                ('title', models.TextField(max_length=700, null=True)),
            ],
        ),
    ]
