# Generated by Django 4.0.10 on 2023-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_image_alter_list_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_blog',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
