# Generated by Django 4.0.10 on 2023-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_list_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_blog',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
